SCHEDULE_KEYWORDS = [
    "lịch học",
    "lịch thi",
    "thời khóa biểu",
    "phòng",
    "phòng học",
    "phòng thi",
    "lớp",
    "giảng viên",
    "học hôm nay",
    "thi khi nào",
    "ngày thi",
    "dths3",
    "thahs",
    "qlhc",
    "kths",
    "luật hình sự",
    "tố tụng hình sự",
    "quản lý hành chính",
    "kỹ thuật hình sự",
]

DOCUMENT_KEYWORDS = [
    "công văn",
    "thông tư",
    "nghị định",
    "luật",
    "luật ban hành",
    "ban hành luật",
    "luật an ninh mạng",
    "luat an ninh mang",
    "luat_an_ninh_mang",
    "đảng viên",
    "đoàn thanh niên",
    "biểu mẫu",
    "đơn",
    "đơn xin phép",
    "đơn nghỉ",
    "tranh thủ",
    "đơn nghỉ tranh thủ",
    "công tác đoàn",
    "tổ chức",
]

STUDY_MATERIAL_KEYWORDS = [
    "học",
    "bài",
    "môn",
    "kiến thức",
    "tài liệu",
    "giáo trình",
    "file",
    "pdf",
    "giải thích",
    "không hiểu",
    "giảng lại",
    "hiểu bài",
    "ôn",
    "ôn tập",
    "luyện",
    "câu hỏi",
    "trắc nghiệm",
    "tóm tắt",
    "tóm lược",
    "ghi nhớ",
    "ý chính",
    "phương pháp học",
    "tự học",
    "ví dụ",
    "minh họa",
    "luật",
    "hình sự",
    "hành chính",
    "tố tụng",
    "nghiệp vụ",
    "pháp luật đại cương",
]

LIBRARY_KEYWORDS = [
    "sách",
    "thư viện",
    "mượn",
    "tìm sách",
    "có sách",
    "còn sách",
    "hết sách",
    "ở đâu",
    "kệ",
    "vị trí",
    "mượn bao lâu",
    "thời gian mượn",
    "luật",
    "hình sự",
    "tố tụng",
    "hành chính",
    "nghiệp vụ",
    "giáo trình luật hình sự",
    "luật tố tụng hình sự",
    "nghiệp vụ công an cơ bản",
    "pháp luật đại cương",
    "giáo trình quản lý hành chính",
    "kỹ thuật hình sự cơ bản",
    "giờ mở cửa",
    "mở cửa",
    "đóng cửa",
    "thủ thư",
    "liên hệ thư viện",
    "mượn tối đa",
    "gia hạn",
    "trả trễ",
    "phạt",
    "isbn",
    "mã tài liệu",
    "tác giả",
    "chỉ đọc tại chỗ",
]

ADMISSION_KEYWORDS = [
    "tuyển sinh",
    "tuyen sinh",
    "chính quy",
    "văn bằng 2",
    "văn bằng hai",
    "van bang 2",
    "van bang hai",
    "bằng đại học thứ 2",
    "bang dai hoc thu 2",
    "vb2",
    "xét tuyển thẳng",
    "xet tuyen thang",
    "thi tuyển",
    "thi tuyen",
    "vb2ca",
    "css",
    "cntt",
    "công nghệ thông tin",
    "tốt nghiệp",
    "đăng ký",
    "liên thông",
    "thạc sĩ",
    "nghiên cứu sinh",
    "vừa học vừa làm",
    "sức khỏe",
    "tiếng anh",
    "chứng chỉ",
    "lý lịch",
    "ngành",
    "thông báo tuyển",
    "chỉ tiêu",
    "phương thức",
    "xét tuyển",
    "bài thi",
    "ca1",
    "ca2",
    "ca3",
    "ca4",
    "tổ hợp",
    "mã trường",
    "mã ngành",
    "phía nam",
    "đối tượng dự tuyển",
    "điều kiện dự tuyển",
    "hồ sơ nhập học",
    "hồ sơ",
    "nhập học",
    "email",
    "mail",
    "liên hệ",
    "website",
    "ngưỡng đầu vào",
    "sơ tuyển",
    "đăng ký sơ tuyển",
    "đăng ký dự tuyển",
    "thủ tục đăng ký",
    "hạn đăng ký",
    "lệ phí",
    "lệ phí sơ tuyển",
    "ưu tiên",
    "điểm thưởng",
    "đào tạo",
    "thời gian đào tạo",
    "chính sách",
    "phân công",
    "phong hàm",
    "trung úy",
    "cách tính điểm",
    "điểm xét tuyển",
    "đxt",
    "điểm cộng",
    "chiều cao",
    "bmi",
    "thị lực",
    "ngành được phép",
    "ngày thi",
    "timeline",
    "lộ trình",
    "checklist",
    "so sánh phương thức",
    "đủ điều kiện",
    "đăng ký được",
    "liên thông",
    "20/09/2026",
    "thông báo 56",
    "56/TB-CAT-PX01",
]

ADMISSION_PRIORITY_KEYWORDS = [
    "tuyển sinh",
    "tuyen sinh",
    "văn bằng 2",
    "văn bằng hai",
    "van bang 2",
    "van bang hai",
    "vb2",
    "vb2ca",
    "css",
    "cntt",
    "công nghệ thông tin",
    "tốt nghiệp",
    "đăng ký",
    "chỉ tiêu",
    "xét tuyển",
    "xét tuyển thẳng",
    "thi tuyển",
    "phương thức",
    "điều kiện",
    "bài thi",
    "ca1",
    "ca2",
    "ca3",
    "ca4",
    "mã trường",
    "mã ngành",
    "phía nam",
    "ngưỡng đầu vào",
    "hồ sơ",
    "nhập học",
    "ielts",
    "chứng chỉ",
    "liên hệ",
    "website",
    "sơ tuyển",
    "đăng ký sơ tuyển",
    "đăng ký dự tuyển",
    "hạn đăng ký",
    "lệ phí",
    "ưu tiên",
    "điểm thưởng",
    "đào tạo",
    "cách tính điểm",
    "điểm xét tuyển",
    "đxt",
    "chiều cao",
    "bmi",
    "thị lực",
    "ngày thi",
    "timeline",
    "lộ trình",
    "checklist",
    "so sánh phương thức",
    "đủ điều kiện",
    "đăng ký được",
    "liên thông",
    "20/09/2026",
]
